/*
 * Generated by XDoclet - Do not edit!
 */
package mfis.tiendavirtual.interfaces;

/**
 * Home interface for GestionPedidos.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GestionPedidosHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GestionPedidos";
   public static final String JNDI_NAME="ejb/GestionPedidos";

   public mfis.tiendavirtual.interfaces.GestionPedidos create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
