/*
 * Generated by XDoclet - Do not edit!
 */
package mfis.tiendavirtual.interfaces;

/**
 * Remote interface for GestionOperador.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GestionOperador
   extends javax.ejb.EJBObject
{
   /**
    * Business method
    */
   public mfis.tiendavirtual.mocks.persistence.Operador getOperador( int id )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public mfis.tiendavirtual.mocks.persistence.Operador getOperador( java.lang.String login )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public mfis.tiendavirtual.mocks.persistence.Pedido siguientePedido( int id )
      throws java.rmi.RemoteException;

}
