/*
 * Generated by XDoclet - Do not edit!
 */
package mfis.tiendavirtual.interfaces;

/**
 * Home interface for GestionOperador.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GestionOperadorHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GestionOperador";
   public static final String JNDI_NAME="ejb/GestionOperador";

   public mfis.tiendavirtual.interfaces.GestionOperador create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
