/*
 * Generated by XDoclet - Do not edit!
 */
package mfis.tiendavirtual.interfaces;

/**
 * Home interface for GestionOferta.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GestionOfertaHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GestionOferta";
   public static final String JNDI_NAME="ejb/GestionOferta";

   public mfis.tiendavirtual.interfaces.GestionOferta create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
