/*
 * Generated by XDoclet - Do not edit!
 */
package mfis.tiendavirtual.interfaces;

/**
 * Remote interface for GestionPedidos.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GestionPedidos
   extends javax.ejb.EJBObject
{
   /**
    * Business method
    */
   public void registrarPedido( mfis.tiendavirtual.mocks.persistence.Carrito c,java.lang.String direccion )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public void actualizarEstado( mfis.tiendavirtual.mocks.persistence.Pedido p,java.lang.String estado,java.util.Date fecha )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public mfis.tiendavirtual.mocks.persistence.Pedido getPedido( int id )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public void anadeBeneficio( mfis.tiendavirtual.mocks.persistence.Pedido p )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public void anadeBeneficio( mfis.tiendavirtual.mocks.persistence.Item i )
      throws java.rmi.RemoteException;

}
