/*
 * Generated by XDoclet - Do not edit!
 */
package mfis.tiendavirtual.interfaces;

/**
 * Remote interface for GestionOperador.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GestionOperador
   extends javax.ejb.EJBObject
{
   /**
    * Business method
    */
   public mfis.tiendavirtual.modelo.objetoNegocio.Operador getOperador( int id )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public mfis.tiendavirtual.modelo.objetoNegocio.Operador getOperador( java.lang.String login )
      throws java.rmi.RemoteException;

   /**
    * Business method
    */
   public mfis.tiendavirtual.modelo.objetoNegocio.Pedido siguientePedido( int id )
      throws java.rmi.RemoteException;
   
   /**
    * Business method
    */
   public java.util.List obtenerPedidosOperador(java.lang.String login)
   		throws java.rmi.RemoteException;
   

}
